SELECT 
	IT.ItemCode
	, IT.ItemName
	, SUM(
		CASE 
			WHEN ISNULL(WH.WhsCode,'') = '01' THEN ISNULL(ITXWH.OnHand,0) ELSE 0 END
		) AS [01]
	, SUM(
		CASE 
			WHEN ISNULL(WH.WhsCode,'') = '02' THEN ISNULL(ITXWH.OnHand,0) ELSE 0 END
		) AS [02]
	, SUM(
		CASE 
			WHEN ISNULL(WH.WhsCode,'') = '03' THEN ISNULL(ITXWH.OnHand,0) ELSE 0 END
		) AS [03]
	, SUM(
		CASE 
			WHEN ISNULL(WH.WhsCode,'') = '04' THEN ISNULL(ITXWH.OnHand,0) ELSE 0 END
		) AS [04]
	, SUM(
		CASE 
			WHEN ISNULL(WH.WhsCode,'') = '05' THEN ISNULL(ITXWH.OnHand,0) ELSE 0 END
		) AS [05]
	, SUM(
		CASE 
			WHEN ISNULL(WH.WhsCode,'') = 'INT' THEN ISNULL(ITXWH.OnHand,0) ELSE 0 END
		) AS [INT]
	, SUM(
		CASE 
			WHEN ISNULL(WH.WhsCode,'') = 'MP' THEN ISNULL(ITXWH.OnHand,0) ELSE 0 END
		) AS [MP]
FROM dbo.OITM AS IT
LEFT JOIN dbo.OITW AS ITXWH ON (ITXWH.ItemCode=IT.ItemCode)
LEFT JOIN dbo.OWHS AS WH ON (WH.WhsCode = ITXWH.WhsCode)
GROUP BY IT.ItemCode,IT.ItemName
HAVING SUM(ISNULL(ITXWH.OnHand, 0)) > 0;